### ISSUE TITLE
配置错误导致大小写失败

### ISSUE THREAD

**Issue by snowcooled** [Jackfinal/laravel-dm8#3]
Dm8/Connectors/DmConnector.php

 protected $options = [
        PDO::CASE_LOWER               => PDO::CASE_LOWER,
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_ORACLE_NULLS       => PDO::NULL_NATURAL,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ,
    ];
    
   第一个配置参数应该是：
   PDO::ATTR_CASE               => PDO::CASE_LOWER,
   
   配置错误，数据库配置字段名强制大写的话，Laravel会报查不到对象属性值的错误。
ErrorException
Undefined index: ...

**Comment by Jackfinal** [comment]
已更新
