### ISSUE TITLE
中文问题

### ISSUE THREAD

**Issue by maxlcoder** [Jackfinal/laravel-dm8#6]
laravel 在 command 模式下，能够支持 中文的条件查询，但是在 php-fpm web 模式测试 不支持 中文，其他的条件查询英文数字等都是 OK 的，这个会是 什么原因 ？

**Comment by Jackfinal** [comment]
您好，您的邮件我已收到，无法亲自回复您的邮件。

**Comment by Jackfinal** [comment]
考虑是不是编码问题，utf-8
