### ISSUE TITLE
类引用错误

### ISSUE THREAD

**Issue by maxlcoder** [Jackfinal/laravel-dm8#8]
![image](https://github.com/Jackfinal/laravel-dm8/assets/18546126/c93b47cf-fc95-47e2-acdf-f2df5131f2c3)

Schema/DmBuilder 文件中存在类引用错误，这里应该是 DmAutoIncrementHelper

**Comment by Jackfinal** [comment]
已修复

**Comment by Jackfinal** [comment]
已修复

**Comment by Jackfinal** [comment]
1
